name = "Nova MTR"
author = "AwesomeKalin55, Quanti"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d55b19655e7a80237e96054d0ea55a0e669016444c9d275264cc2e1d8e7532a"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
