name = "Nova MTR"
author = "AwesomeKalin55, Quanti"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc672ad8e8372b9529ce04405130c471a5d1f75234767e3d018595cc7dd3c188"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
