name = "Nova MTR"
author = "AwesomeKalin55, Quanti"
version = "16"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66da67b05a34f5b6f0ca3582e7a1a4a58718019a6abe5b72f11bb61c8017f545"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
