name = "Nova MTR"
author = "AwesomeKalin55, Quanti"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0df3a818e57d865e4c57e704f87644baf50a9929b7d1e059ca70655d002aef3b"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
