name = "Nova MTR"
author = "AwesomeKalin55, Quanti"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea99447eb708fd37037d095790fb09374f79b67216cbfe7ddde1b0214f2ade4b"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
