name = "Nova MTR"
author = "AwesomeKalin55, Quanti"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7f54ad175d3608e305acb13e8270d7c75d80c527e4966960c06d5d849265eff"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
